apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: habana-cluster
  region: us-east-1
  version: "1.25"
availabilityZones: ["us-east-1a", "us-east-1b"]
managedNodeGroups:
- name: ctrl-plain-ng
  instanceType: m5a.2xlarge
  volumeSize: 100
  minSize: 3
  maxSize: 6
  desiredCapacity: 3
  privateNetworking: true
  iam:
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    - arn:aws:iam::aws:policy/AmazonS3FullAccess
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    - arn:aws:iam::aws:policy/AmazonEC2FullAccess
    withAddonPolicies:
      autoScaler: true
  tags:
    k8s.io/cluster-autoscaler/enabled: 'true'
    itays.world/baked-beans: 'gravy'
    nodegroup-role: worker
- name: worker-ng
  ami: ami-05127c866f8ceab9f
  # for us-west-2: ami-0fc317e7288476acf
  amiFamily: AmazonLinux2
  availabilityZones: ["us-east-1a"]
  overrideBootstrapCommand: |
    #!/bin/bash
    /etc/eks/bootstrap.sh habana-cluster
  # /etc/eks/bootstrap.sh cluster-name ## IMPORTANT!
  instanceType: dl1.24xlarge
  volumeSize: 100
  minSize: 0
  maxSize: 1
  desiredCapacity: 0
  privateNetworking: true
  iam:
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    - arn:aws:iam::aws:policy/AmazonS3FullAccess
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    withAddonPolicies:
      autoScaler: true
  tags:
    k8s.io/cluster-autoscaler/enabled: 'true'
    itays.world/baked-beans: 'butter'
    nodegroup-role: worker
