apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mnd-endpoints-test
  region: us-east-1
  version: "1.22"
managedNodeGroups:
- name: web-app-ng
  instanceType: m5a.2xlarge
  volumeSize: 100
  minSize: 3
  maxSize: 6
  desiredCapacity: 3
  privateNetworking: true
  iam:
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    - arn:aws:iam::aws:policy/AmazonS3FullAccess
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    withAddonPolicies:
      autoScaler: true
  tags:
    k8s.io/cluster-autoscaler/enabled: 'true'
    jacks.world/baked-beans: 'gravy'
    nodegroup-role: worker
