kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: host-networking-pods
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - vmware-system-privileged # Name of the PodSecurityPolicy
  verbs:
  - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-default
subjects:
- kind: Group
  name: system:serviceaccounts
  namespace: kube-system
- kind: User
  name: replicaset-controller 
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:serviceaccounts:webapp
  namespace: webapp
- kind: User
  name: job-controller
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: host-networking-pods # Referencing the ClusterRole above
  apiGroup: rbac.authorization.k8s.io